

USE GOXORM_DB
GO

IF DB_NAME() <> N'GOXORM_DB' SET NOEXEC ON
GO

--
-- Create table [dbo].[CONTACTS_00_01]
--
PRINT (N'Create table [dbo].[CONTACTS_00_01]')
GO
IF OBJECT_ID(N'dbo.CONTACTS_00_01', 'U') IS NULL
CREATE TABLE dbo.CONTACTS_00_01 (
  CONTACT_01_ID bigint NOT NULL,
  CONTACT_CODIGO bigint NOT NULL,
  CONTACT_CELL varchar(50) NULL,
  CONTACT_PHONE varchar(50) NULL,
  CONTACT_EMAIL varchar(50) NULL,
  CONSTRAINT PK_CONTACTS_00_01_CONTACT_01_ID PRIMARY KEY CLUSTERED (CONTACT_01_ID)
)
ON [PRIMARY]
GO

--
-- Create table [dbo].[CONTACTS_00]
--
PRINT (N'Create table [dbo].[CONTACTS_00]')
GO
IF OBJECT_ID(N'dbo.CONTACTS_00', 'U') IS NULL
CREATE TABLE dbo.CONTACTS_00 (
  CONTACT_CODIGO bigint NOT NULL,
  CONTACT_BIRTHDATE date NULL,
  CONTACT_NAME varchar(50) NULL,
  CONTACT_LASTNAME varchar(50) NULL,
  CONTACT_SALARY decimal(18, 2) NULL,
  CONTACT_AGE int NULL,
  CONSTRAINT PK_CONTACTS_00_CONTACT_ID PRIMARY KEY CLUSTERED (CONTACT_CODIGO)
)
ON [PRIMARY]
GO

--
-- Create sequence [dbo].[SEQ_CONTACTS_CODIGO]
--
PRINT (N'Create sequence [dbo].[SEQ_CONTACTS_CODIGO]')
GO
IF OBJECT_ID(N'dbo.SEQ_CONTACTS_CODIGO', 'SO') IS NULL
CREATE SEQUENCE dbo.SEQ_CONTACTS_CODIGO
  AS bigint
  START WITH 1
  INCREMENT BY 1
  NO CYCLE
  NO CACHE
GO

--
-- Create sequence [dbo].[SEQ_CONTACTS_01_ID]
--
PRINT (N'Create sequence [dbo].[SEQ_CONTACTS_01_ID]')
GO
IF OBJECT_ID(N'dbo.SEQ_CONTACTS_01_ID', 'SO') IS NULL
CREATE SEQUENCE dbo.SEQ_CONTACTS_01_ID
  AS bigint
  START WITH 1
  INCREMENT BY 1
  NO CYCLE
  NO CACHE
GO
SET NOEXEC OFF
GO